config/routes.rb
Rails.application.routes.draw do
  resources :patients do
    collection do
      post :process_csv
      get :upload
      get :stats
    end
  end
  root "patients#upload"
  get 'migration_logs', to: 'migration_logs#index', as: 'migration_logs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/migration_log.rb
class MigrationLog < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :vitals, dependent: :destroy

  validates :health_identifier, presence: true, uniqueness: { scope: :health_identifier_province }
end

app/models/vital.rb
class Vital < ApplicationRecord
  belongs_to :patient

  validates :vital_type, :measurement, :units, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/migration_logs_controller.rb
# app/controllers/migration_logs_controller.rb
class MigrationLogsController < ApplicationController
  def index
    @migration_logs = MigrationLog.all.order(migration_date: :desc)
  end
end

app/controllers/patients_controller.rb
require 'csv'

class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]
  def index
    @patients = Patient.all.order(:last_name, :first_name)
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  def upload
  end

  def process_csv
    file = params[:file]
    return redirect_to root_path, alert: "No file uploaded" unless file

    start_time = Time.now
    csv_headers = CSV.open(file.path, &:readline)

    if csv_headers.include?('vital_type')
      VitalDataImportService.new(file).process
    else
      PatientImportService.new(file).import_data
    end

    @imported_patients_count = Patient.count
    @import_duration = Time.now - start_time

    redirect_to stats_patients_path
  end

  def stats
    @patients_by_province = Patient.group(:address_province).count
    @patients_by_sex = Patient.group(:sex).count
    @patients_by_vital_type = Vital.group(:vital_type).count
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:health_identifier, :first_name, :last_name, :date_of_birth, :sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthClinicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/migration_logs/index.html.erb
<h1 class="mb-4 text-center">Migration Statistics</h1>

<div class="mb-4 text-center">
    <%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-success btn-lg me-2' %>
    <%= link_to 'Patient Statistics', stats_patients_path, class: 'btn btn-info btn-lg' %>
    <%= link_to 'Patients Managment', patients_path, class: 'btn btn btn-warning btn-lg' %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Date</th>
        <th>Patients Imported</th>
        <th>Migration Duration (seconds)</th>
      </tr>
    </thead>
    <tbody>
      <% @migration_logs.each do |log| %>
        <tr>
          <td><%= log.migration_date.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td><%= log.patients_imported %></td>
          <td><%= log.migration_duration.round(2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/_form.html.erb
<h1 class="text-center mb-4">
  <%= action_name == 'new' ? 'Add New Patient' : 'Edit Patient' %>
</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card shadow-sm">
        <div class="card-body">
          <%= form_with(model: @patient, local: true) do |form| %>
            <div class="mb-4">
              <%= form.label :health_identifier, class: 'form-label' %>
              <%= form.text_field :health_identifier, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :health_identifier_province, class: 'form-label' %>
              <%= form.text_field :health_identifier_province, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :first_name, class: 'form-label' %>
              <%= form.text_field :first_name, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :last_name, class: 'form-label' %>
              <%= form.text_field :last_name, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :middle_name, class: 'form-label' %>
              <%= form.text_field :middle_name, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :phone, class: 'form-label' %>
              <%= form.text_field :phone, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>
            </div>

            <div class="mb-4">
              <%= form.label :email, class: 'form-label' %>
              <%= form.email_field :email, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :address1, class: 'form-label' %>
              <%= form.text_field :address1, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :address2, class: 'form-label' %>
              <%= form.text_field :address2, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :address_province, class: 'form-label' %>
              <%= form.text_field :address_province, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :address_city, class: 'form-label' %>
              <%= form.text_field :address_city, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :address_postal_code, class: 'form-label' %>
              <%= form.text_field :address_postal_code, class: 'form-control' %>
            </div>

            <div class="mb-4">
              <%= form.label :date_of_birth, class: 'form-label' %>
              <%= form.date_field :date_of_birth, class: 'form-control datepicker', autocomplete: 'off' %>
            </div>

            <div class="mb-4">
              <%= form.label :sex, class: 'form-label' %>
              <%= form.select :sex, [['Male', 'Male'], ['Female', 'Female'], ['Other', 'Other']], { include_blank: true }, class: 'form-select' %>
            </div>

            <div class="text-center">
              <%= form.submit class: 'btn btn-primary btn-lg' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1 class="text-center my-4">Patient Management</h1>

<div class="container">
  <!-- Navigation Buttons -->
  <div class="text-center mb-4">
    <%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-success btn-lg me-2' %>
    <%= link_to 'Upload CSV', upload_patients_path, class: 'btn btn-primary btn-lg me-2' %>
    <%= link_to 'Patient Statistics', stats_patients_path, class: 'btn btn-info btn-lg' %>
    <%= link_to 'Migration Logs', migration_logs_path, class: 'btn btn-secondary btn-lg' %>
  </div>

  <!-- Patient Table -->
  <div class="card">
    <div class="card-header">
      <h5 class="mb-0">Patients</h5>
    </div>
    <div class="card-body">
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th>Health Identifier</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date of Birth</th>
            <th>Sex</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.health_identifier %></td>
              <td><%= patient.first_name %></td>
              <td><%= patient.last_name %></td>
              <td><%= patient.date_of_birth ? patient.date_of_birth.strftime("%Y-%m-%d") : 'N/A' %></td>
              <td><%= patient.sex %></td>
              <td>
                <%= link_to 'Show', patient_path(patient), class: 'btn btn-info btn-sm me-1' %>
                <%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-warning btn-sm me-1' %>
                <%= link_to 'Delete', patient_path(patient), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

app/views/patients/process.html.erb
<h1>Patients#process</h1>
<p>Find me in app/views/patients/process.html.erb</p>

app/views/patients/show.html.erb
<h1 class="text-center my-4">Patient Details</h1>

<div class="container">
  <div class="card">
    <div class="card-header">
      <h5 class="mb-0">Patient Information</h5>
    </div>
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3">Health Identifier:</dt>
        <dd class="col-sm-9"><%= @patient.health_identifier %></dd>

        <dt class="col-sm-3">First Name:</dt>
        <dd class="col-sm-9"><%= @patient.first_name %></dd>

        <dt class="col-sm-3">Last Name:</dt>
        <dd class="col-sm-9"><%= @patient.last_name %></dd>

        <dt class="col-sm-3">Date of Birth:</dt>
        <dd class="col-sm-9"><%= @patient.date_of_birth ? @patient.date_of_birth.strftime("%Y-%m-%d") : 'N/A' %></dd>

        <dt class="col-sm-3">Sex:</dt>
        <dd class="col-sm-9"><%= @patient.sex %></dd>

        <dt class="col-sm-3">Phone:</dt>
        <dd class="col-sm-9"><%= @patient.phone %></dd>

        <dt class="col-sm-3">Email:</dt>
        <dd class="col-sm-9"><%= @patient.email %></dd>

        <dt class="col-sm-3">Address:</dt>
        <dd class="col-sm-9">
          <%= @patient.address1 %><br>
          <%= @patient.address2.present? ? "#{@patient.address2}<br>" : "" %>
          <%= @patient.address_city %>, <%= @patient.address_province %> <%= @patient.address_postal_code %>
        </dd>
      </dl>

      <div class="text-center mt-4">
        <%= link_to 'Edit', edit_patient_path(@patient), class: 'btn btn-warning me-2' %>
        <%= link_to 'Back to List', patients_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/patients/stats.html.erb
<h1 class="mb-4">Patient Statistics</h1>

<div class="mb-4">
  <%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-success btn-lg me-2' %>
  <%= link_to 'Migration Logs', migration_logs_path, class: 'btn btn-secondary btn-lg' %>
  <%= link_to 'Patients Managment', patients_path, class: 'btn btn btn-warning btn-lg' %>
</div>

<div class="mb-4">
  <h2 class="mb-3">Patients by Province</h2>
  <%= column_chart @patients_by_province, class: 'img-fluid' %>
</div>

<div class="mb-4">
  <h2 class="mb-3">Patients by Sex</h2>
  <%= pie_chart @patients_by_sex, class: 'img-fluid' %>
</div>

<div>
  <h2 class="mb-3">Vitals by Type</h2>
  <%= bar_chart @patients_by_vital_type, class: 'img-fluid' %>
</div>

app/views/patients/upload.html.erb
<h1 class="text-center my-4">Patient Management</h1>

<div class="container">
  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">Upload Patient or Vital CSV File</h5>
    </div>
    <div class="card-body">
      <%= form_with url: process_csv_patients_path, local: true, method: :post, multipart: true do |form| %>
        <div class="mb-3">
          <%= form.label :file, "Choose a CSV File to Upload", class: "form-label" %>
          <%= form.file_field :file, accept: ".csv", class: "form-control" %>
        </div>
        
        <div class="text-center">
          <%= form.submit "Import CSV", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Button to Manually Add Patient -->
  <div class="text-center mb-4">
    <%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-success btn-lg me-2' %>
    <%= link_to 'Patient Statistics', stats_patients_path, class: 'btn btn-info btn-lg' %>
    <%= link_to 'Migration Logs', migration_logs_path, class: 'btn btn-secondary btn-lg' %>
    <%= link_to 'Patients Managment', patients_path, class: 'btn btn btn-warning btn-lg' %>
  </div>
</div>